// Incrementado automaticamente a cada publicação via Admin → GitHub
const PRODUTOS_VERSAO = 0;

const PRODUTOS_INICIAIS = [
  // ── RIPADOS ──────────────────────────────────────────────────────────────
  { codigo: "974",  produto: "RIPADO GARAPA COMERCIAL 6,5 CM",                    valor: 189.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "972",  produto: "RIPADO GARAPA FRIZADO EXTRA 6,5 CM",               valor: 294.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "973",  produto: "RIPADO GARAPA EXTRA 6,5 CM",                        valor: 262.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "975",  produto: "RIPADO IPE COMERCIAL 6,5 CM",                       valor: 189.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "976",  produto: "RIPADO IPE EXTRA 6,5 CM",                           valor: 304.50,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "977",  produto: "RIPADO IPE EXTRA FRIZADO 6,5 CM",                  valor: 325.50,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "960",  produto: "RIPADO CUMARU CHANPANHE EXTRA 6,5 CM",             valor: 315.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "961",  produto: "RIPADO CUMARU CHANPANHE EXTRA FRIZADO 6,5 CM",     valor: 315.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "959",  produto: "RIPADO CUMARU CHANPANHE EXTRA 5 CM",               valor: 294.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "962",  produto: "RIPADO CUMARU CHANPANHE COMERCIAL FRIZADO 6,5 CM", valor: 189.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "963",  produto: "RIPADO CUMARU CHANPANHE COMERCIAL 6,5 CM",         valor: 210.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "964",  produto: "RIPADO CUMARU CHANPANHE COMERCIAL 5 CM",           valor: 210.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "968",  produto: "RIPADO CUMARU ROSA EXTRA 6,5 CM",                  valor: 262.50,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "971",  produto: "RIPADO CUMARU ROSA FRIZADO EXTRA 6,5 CM",          valor: 294.00,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "969",  produto: "RIPADO CUMARU ROSA EXTRA 5 CM",                    valor: 262.50,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "967",  produto: "RIPADO CUMARU ROSA COMERCIAL 6,5 CM",              valor: 220.50,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "965",  produto: "RIPADO CUMARU ROSA COMERCIAL 5 CM",                valor: 199.50,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "966",  produto: "RIPADO CUMARU ROSA COMERCIAL 4 CM",                valor: 199.50,  categoria: "RIPADOS",     subcategoria: "" },
  { codigo: "970",  produto: "RIPADO CUMARU ROSA EXTRA 4 CM",                    valor: 199.50,  categoria: "RIPADOS",     subcategoria: "" },

  // ── ASSOALHOS ────────────────────────────────────────────────────────────
  { codigo: "1142", produto: "ASOALHO GARAPA EXTRA 6,5 CM",                      valor: 262.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1143", produto: "ASOALHO GARAPA COMERCIAL 6,5 CM",                  valor: 157.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1002", produto: "ASOALHO IPE EXTRA 15 CM",                          valor: 335.00,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1001", produto: "ASOALHO IPE EXTRA 10 CM",                          valor: 315.00,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1000", produto: "ASOALHO IPE EXTRA 6,5 CM",                         valor: 305.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1003", produto: "ASOALHO IPE COMERCIAL 15 CM",                      valor: 199.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1005", produto: "ASOALHO IPE COMERCIAL 6,5 CM",                     valor: 199.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1004", produto: "ASOALHO CURTO IPE COMERCIAL 10 CM",                valor: 125.00,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1016", produto: "ASOALHO JATOBA EXTRA 15 CM",                       valor: 304.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1015", produto: "ASOALHO JATOBA EXTRA 10 CM",                       valor: 304.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1014", produto: "ASOALHO JATOBA EXTRA 6,5 CM",                      valor: 283.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1012", produto: "ASOALHO JATOBA COMERCIAL 10 CM",                   valor: 136.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1011", produto: "ASOALHO JATOBA COMERCIAL 15 CM",                   valor: 136.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1013", produto: "ASOALHO JATOBA COMERCIAL 6,5 CM",                  valor: 136.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "995",  produto: "ASOALHO CUMARU CHANPANHE EXTRA 5 CM",              valor: 304.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "996",  produto: "ASOALHO CUMARU CHANPANHE EXTRA 6,5 CM",            valor: 304.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "997",  produto: "ASOALHO CUMARU CHANPANHE EXTRA 10 CM",             valor: 315.00,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "998",  produto: "ASOALHO CUMARU CHANPANHE EXTRA 15 CM",             valor: 315.00,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "999",  produto: "ASOALHO CUMARU CHANPANHE EXTRA 15 CM (CÓPIA)",     valor: 335.00,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "986",  produto: "ASOALHO CUMARU ROSA EXTRA 5 CM",                   valor: 273.00,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "987",  produto: "ASOALHO CUMARU ROSA EXTRA 6,5 CM",                 valor: 273.00,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "988",  produto: "ASOALHO CUMARU ROSA EXTRA 10 CM",                  valor: 273.00,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "889",  produto: "ASOALHO CUMARU ROSA EXTRA 15 CM",                  valor: 315.00,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "990",  produto: "ASOALHO CUMARU ROSA COMERCIAL 5 CM",               valor: 199.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "991",  produto: "ASOALHO CUMARU ROSA COMERCIAL 4 CM",               valor: 199.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "992",  produto: "ASOALHO CUMARU ROSA COMERCIAL 6,5 CM",             valor: 199.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "993",  produto: "ASOALHO CUMARU ROSA COMERCIAL 10 CM",              valor: 199.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "994",  produto: "ASOALHO CUMARU ROSA COMERCIAL 15 CM",              valor: 199.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1017", produto: "ASOALHO MUIRACATIARA COMERCIAL 15 CM",             valor: 136.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1018", produto: "ASOALHO MUIRACATIARA COMERCIAL 10 CM",             valor: 136.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1019", produto: "ASOALHO MUIRACATIARA COMERCIAL 10 CM",             valor: 136.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1006", produto: "ASOALHO ROXINHO COMERCIAL 6,5 CM",                 valor: 136.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1007", produto: "ASOALHO ROXINHO COMERCIAL 5 CM",                   valor: 136.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1008", produto: "ASOALHO ROXINHO COMERCIAL 10 CM",                  valor: 136.50,  categoria: "ASSOALHOS",   subcategoria: "" },
  { codigo: "1009", produto: "ASOALHO ROXINHO COMERCIAL 15 CM",                  valor: 136.50,  categoria: "ASSOALHOS",   subcategoria: "" },

  // ── DECKS ────────────────────────────────────────────────────────────────
  { codigo: "1026", produto: "DECK CUMARU CHANPANHE EXTRA 10 CM",                valor: 315.00,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1020", produto: "DECK CUMARU ROSA EXTRA 7 CM",                      valor: 273.00,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1021", produto: "DECK CUMARU ROSA EXTRA 10 CM",                     valor: 273.00,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1022", produto: "DECK CUMARU ROSA EXTRA CURTO 10 CM",               valor: 166.95,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1023", produto: "DECK CUMARU ROSA EXTRA CURTO 7 CM",                valor: 166.95,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1024", produto: "DECK CUMARU ROSA COMERCIAL CURTO 7 CM",            valor: 168.00,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1025", produto: "DECK CUMARU ROSA COMERCIAL CURTO 10 CM",           valor: 168.00,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1027", produto: "DECK CUMARU CHANPANHE COMERCIAL 7 CM",             valor: 199.50,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1036", produto: "DECK GARAPA EXTRA 10 CM",                          valor: 262.50,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1037", produto: "DECK GARAPA EXTRA 7 CM",                           valor: 262.50,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1034", produto: "DECK GARAPA CURTO 7 CM",                           valor: 157.50,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1035", produto: "DECK GARAPA CURTO 10 CM",                          valor: 157.50,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1038", produto: "DECK GARAPA COMERCIAL 7 CM",                       valor: 157.50,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1039", produto: "DECK GARAPA COMERCIAL 10 CM",                      valor: 157.50,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1030", produto: "DECK IPE EXTRA 10 CM",                             valor: 273.00,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1031", produto: "DECK IPE EXTRA 7 CM",                              valor: 273.00,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1028", produto: "DECK IPE COMERCIAL 7 CM",                          valor: 168.00,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1029", produto: "DECK IPE COMERCIAL 10 CM",                         valor: 168.00,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1032", produto: "DECK IPE COMERCIAL CURTO 10 CM",                   valor: 126.00,  categoria: "DECKS",       subcategoria: "" },
  { codigo: "1033", produto: "DECK IPE COMERCIAL CURTO 7 CM",                    valor: 126.00,  categoria: "DECKS",       subcategoria: "" },

  // ── LAMBRIL ──────────────────────────────────────────────────────────────
  { codigo: "1244", produto: "LAMBRIL TAUARI EXTRA 1 X 10",                      valor: 168.00,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "951",  produto: "LAMBRIL PINUS EXTRA 1 X 10",                       valor: 37.80,   categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "945",  produto: "LAMBRIL ANGELIM PEDRA EXTRA 1 X 10",               valor: 131.25,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "944",  produto: "LAMBRIL ANGELIM AMARGOSO EXTRA 1 X 10",            valor: 131.25,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "1144", produto: "LAMBRIL CURTO ANGELIM PEDRA EXTRA 1 X 10",         valor: 94.50,   categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "1145", produto: "LAMBRIL CURTO CEDRINHO EXTRA 1 X 10",              valor: 105.00,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "946",  produto: "LAMBRIL CEDRINHO EXTRA 1 X 10",                    valor: 147.00,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "1243", produto: "LAMBRIL CEDRINHO MEXCLADO 1 X 10",                 valor: 120.75,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "958",  produto: "LAMBRIL CUMARU CHANPANHE EXTRA 1 X 10",            valor: 220.50,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "1234", produto: "LAMBRIL CUMARU ROSA EXTRA 1 X 10",                 valor: 231.00,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "1041", produto: "LAMBRIL CUMARU ROSA EXTRA 1 X 10 CM",              valor: 180.00,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "1226", produto: "LAMBRIL CUMARU ROSA EXTRA 2CM X 7CM",              valor: 252.00,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "947",  produto: "LAMBRIL CUMARU ROSA COMERCIAL 1 X 10",             valor: 189.00,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "948",  produto: "LAMBRIL CUMARU ROSA COMERCIAL 1 X 10 (B)",         valor: 147.00,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "949",  produto: "LAMBRIL IPE EXTRA 1 X 10",                         valor: 199.50,  categoria: "LAMBRIL",     subcategoria: "" },
  { codigo: "950",  produto: "LAMBRIL IPE COMERCIAL 1 X 10",                     valor: 157.50,  categoria: "LAMBRIL",     subcategoria: "" },

  // ── FECHADURAS 3F ─────────────────────────────────────────────────────────
  { codigo: "451",  produto: "FECHADURA 3F BICO DE PAPAGAIO CR",                 valor: 78.80,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "452",  produto: "FECHADURA 3F 4145 CR",                             valor: 126.30,  categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "446",  produto: "FECHADURA 3F 711 BAN CR",                          valor: 89.50,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "445",  produto: "FECHADURA 3F 711 EXT CR",                          valor: 89.50,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "448",  produto: "FECHADURA 3F 713 BAN CR",                          valor: 84.21,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "447",  produto: "FECHADURA 3F 713 EXT CR",                          valor: 72.30,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "287",  produto: "FECHADURA 3F 718 WC CR",                           valor: 61.05,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "286",  produto: "FECHADURA 3F 718 EXT CR",                          valor: 67.40,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "450",  produto: "FECHADURA 3F 720 BAN CR",                          valor: 84.25,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "449",  produto: "FECHADURA 3F 720 EXT CR",                          valor: 94.74,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "456",  produto: "FECHADURA 3F 740 BAN PP",                          valor: 89.47,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "455",  produto: "FECHADURA 3F 740 BAN CR",                          valor: 89.47,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "454",  produto: "FECHADURA 3F 740 EXT PP",                          valor: 94.74,   categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "453",  produto: "FECHADURA 3F 740 EXT CR",                          valor: 100.00,  categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "290",  produto: "FECHADURA 3F 841 EXT PP",                          valor: 189.00,  categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "288",  produto: "FECHADURA 3F 841 EXT CR",                          valor: 189.00,  categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "291",  produto: "FECHADURA 3F 841 WC PP",                           valor: 189.00,  categoria: "FECHADURAS",  subcategoria: "3F" },
  { codigo: "289",  produto: "FECHADURA 3F 841 WC CR",                           valor: 189.00,  categoria: "FECHADURAS",  subcategoria: "3F" },

  // ── FECHADURAS IMAB ───────────────────────────────────────────────────────
  { codigo: "301",  produto: "FECHADURA IMAB 2441 INOX 1/2 CIL 3000 C/ BOTAO PP", valor: 168.45, categoria: "FECHADURAS", subcategoria: "IMAB" },
  { codigo: "300",  produto: "FECHADURA IMAB 2441 INOX 1/2 CIL 3000 C/ BOTAO XP", valor: 168.40, categoria: "FECHADURAS", subcategoria: "IMAB" },
  { codigo: "303",  produto: "FECHADURA IMAB 2441 INOX CIL 3000 PP",             valor: 194.70,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "302",  produto: "FECHADURA IMAB 2441 INOX CIL 3000 XP",             valor: 204.99,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "299",  produto: "FECHADURA IMAB 2791 INOX CIL 3000 70MM PP",        valor: 176.08,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "298",  produto: "FECHADURA IMAB 2791 INOX CIL 3000 70MM XP",        valor: 150.15,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "277",  produto: "FECHADURA IMAB AUXILIAR ASA AVIAO EXT CR",         valor: 168.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "279",  produto: "FECHADURA IMAB AUXILIAR ASA AVIAO EXT PP",         valor: 168.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "278",  produto: "FECHADURA IMAB AUXILIAR ASA AVIAO WC CR",          valor: 168.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "280",  produto: "FECHADURA IMAB AUXILIAR ASA AVIAO WC PP",          valor: 168.50,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "281",  produto: "FECHADURA IMAB AUXILIAR ASA AVIAO WC PP (B)",      valor: 168.45,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "255",  produto: "FECHADURA IMAB LEXI EXT CR 55MM",                  valor: 315.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "264",  produto: "FECHADURA IMAB LEXI EXT PP 55MM",                  valor: 300.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "256",  produto: "FECHADURA IMAB LEXI WC CR 55MM",                   valor: 273.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "265",  produto: "FECHADURA IMAB LEXI WC PP 55MM",                   valor: 273.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "253",  produto: "FECHADURA IMAB LOGUS EXT CR 55MM",                 valor: 267.80,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "262",  produto: "FECHADURA IMAB LOGUS EXT PP 55MM",                 valor: 267.80,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "254",  produto: "FECHADURA IMAB LOGUS WC CR 55MM",                  valor: 227.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "263",  produto: "FECHADURA IMAB LOGUS WC PP 55MM",                  valor: 227.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "251",  produto: "FECHADURA IMAB MALBA EXT CR 55MM",                 valor: 254.10,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "266",  produto: "FECHADURA IMAB MALBA EXT PP 55MM",                 valor: 254.10,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "309",  produto: "FECHADURA IMAB MALBA EZ1750 PP CILINDRO",          valor: 221.60,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "252",  produto: "FECHADURA IMAB MALBA WC CR 55MM",                  valor: 221.60,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "267",  produto: "FECHADURA IMAB MALBA WC PP 55MM",                  valor: 221.60,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "249",  produto: "FECHADURA IMAB METRO LIGHT EXT CR 55MM",           valor: 210.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "268",  produto: "FECHADURA IMAB METRO LIGHT EXT PP",                valor: 210.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "250",  produto: "FECHADURA IMAB METRO LIGHT WC CR 55MM",            valor: 180.80,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "269",  produto: "FECHADURA IMAB METRO LIGHT WC PP",                 valor: 190.30,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "257",  produto: "FECHADURA IMAB ODIN EXT CR 40MM",                  valor: 122.50,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "270",  produto: "FECHADURA IMAB ODIN EXT PP 40MM",                  valor: 122.30,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "258",  produto: "FECHADURA IMAB ODIN WC CR 40MM",                   valor: 101.10,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "271",  produto: "FECHADURA IMAB ODIN WC PP 40MM",                   valor: 94.80,   categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "457",  produto: "FECHADURA IMAB ROLETE 4700 70MM PP",               valor: 476.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "274",  produto: "FECHADURA IMAB ROLETE 4700 CR 70MM",               valor: 476.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "275",  produto: "FECHADURA IMAB ROLETE 4700 CR 90MM",               valor: 550.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "571",  produto: "FECHADURA IMAB ROLETE 4700 PP 90MM",               valor: 550.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "259",  produto: "FECHADURA IMAB TESS EXT CR 40MM",                  valor: 175.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "272",  produto: "FECHADURA IMAB TESS EXT PP 40MM",                  valor: 175.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "260",  produto: "FECHADURA IMAB TESS WC CR 40MM",                   valor: 165.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },
  { codigo: "273",  produto: "FECHADURA IMAB TESS WC PP 40MM",                   valor: 165.00,  categoria: "FECHADURAS",  subcategoria: "IMAB" },

  // ── PUXADORES ─────────────────────────────────────────────────────────────
  { codigo: "615",  produto: "PUXADOR CONCHA 15CM INOX",                         valor: 71.50,   categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "616",  produto: "PUXADOR CONCHA 15CM PRETO",                        valor: 71.50,   categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "613",  produto: "PUXADOR CONCHA 25CM INOX",                         valor: 121.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "614",  produto: "PUXADOR CONCHA 25CM PRETO",                        valor: 121.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "675",  produto: "PUXADOR MADRI 80 CM CR",                           valor: 577.50,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "338",  produto: "PUXADOR BLACK 40X10X1000",                         valor: 330.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "339",  produto: "PUXADOR BLACK 40X10X1200",                         valor: 330.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "336",  produto: "PUXADOR BLACK 40X10X600",                          valor: 236.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "337",  produto: "PUXADOR BLACK 40X10X800",                          valor: 286.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "321",  produto: "PUXADOR BLACK 40X20X1000",                         valor: 407.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "322",  produto: "PUXADOR BLACK 40X20X1200",                         valor: 440.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "320",  produto: "PUXADOR BLACK 40X20X800",                          valor: 352.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "329",  produto: "PUXADOR BLACK 50X20X1000",                         valor: 495.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "330",  produto: "PUXADOR BLACK 50X20X1200",                         valor: 528.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "331",  produto: "PUXADOR BLACK 50X20X1500",                         valor: 682.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "332",  produto: "PUXADOR BLACK 50X20X2000",                         valor: 880.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "328",  produto: "PUXADOR BLACK 50X20X800",                          valor: 430.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "335",  produto: "PUXADOR INOX 40X10X1000",                          valor: 286.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "333",  produto: "PUXADOR INOX 40X10X600",                           valor: 220.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "334",  produto: "PUXADOR INOX 40X10X800",                           valor: 264.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "318",  produto: "PUXADOR INOX 40X20X1000",                          valor: 379.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "319",  produto: "PUXADOR INOX 40X20X1200",                          valor: 412.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "317",  produto: "PUXADOR INOX 40X20X800",                           valor: 330.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "324",  produto: "PUXADOR INOX 50X20X1000",                          valor: 440.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "325",  produto: "PUXADOR INOX 50X20X1200",                          valor: 484.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "326",  produto: "PUXADOR INOX 50X20X1500",                          valor: 638.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "327",  produto: "PUXADOR INOX 50X20X2000",                          valor: 792.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "323",  produto: "PUXADOR INOX 50X20X800",                           valor: 412.00,  categoria: "PUXADORES",   subcategoria: "" },
  { codigo: "346",  produto: "PUXADOR SOLIDA INOX 40X10X1200",                   valor: 363.00,  categoria: "PUXADORES",   subcategoria: "" },

  // ── PORTAS - PRANCHETA ───────────────────────────────────────────────────
  { codigo: "53",   produto: "PORTA PRANCHETA IPUMIRIM 2,10 X 60",               valor: 283.50,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "54",   produto: "PORTA PRANCHETA IPUMIRIM 2,10 X 70",               valor: 283.50,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "55",   produto: "PORTA PRANCHETA IPUMIRIM 2,10 X 80",               valor: 283.50,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "56",   produto: "PORTA PRANCHETA IPUMIRIM 2,10 X 90",               valor: 341.77,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "57",   produto: "PORTA PRANCHETA IPUMIRIM 2,10 X 1 MT",             valor: 441.00,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "381",  produto: "PORTA PRANCHETA IPUMIRIM 2,10 X 1,00",             valor: 441.00,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "656",  produto: "PORTA PRANCHETA IPUMIRIM 2,40 X 1,20",             valor: 1102.50, categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "382",  produto: "PORTA PRANCHETA IPUMIRIM 2,10 X 1,20",             valor: 870.97,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "383",  produto: "PORTA PRANCHETA IPUMIRIM 2,40 X 0,60",             valor: 441.00,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "384",  produto: "PORTA PRANCHETA IPUMIRIM 2,40 X 0,70",             valor: 441.00,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "385",  produto: "PORTA PRANCHETA IPUMIRIM 2,40 X 0,80",             valor: 441.00,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "386",  produto: "PORTA PRANCHETA IPUMIRIM 2,40 X 0,90",             valor: 529.20,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "387",  produto: "PORTA PRANCHETA IPUMIRIM 2,40 X 1,00",             valor: 573.30,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "58",   produto: "PORTA PRANCHETA SCHILINDEWIN 2,10 X 60",           valor: 220.50,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "59",   produto: "PORTA PRANCHETA SCHILINDEWIN 2,10 X 70",           valor: 220.50,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "60",   produto: "PORTA PRANCHETA SCHILINDEWIN 2,10 X 80",           valor: 220.50,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "62",   produto: "PORTA PRANCHETA SCHILINDEWIN 2,10 X 90",           valor: 273.00,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "61",   produto: "PORTA PRANCHETA SCHILINDEWIN 2,10 X 1,00",         valor: 341.77,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "527",  produto: "PORTA PRANCHETA SCHILINDEWIN 2,10 X 100",          valor: 357.00,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "1238", produto: "PORTA PRANCHETA SCHILINDEWIN 2,10 X 110",          valor: 980.00,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
  { codigo: "1239", produto: "PORTA PRANCHETA SCHILINDEWIN 2,10 X 130",          valor: 980.00,  categoria: "PORTAS",      subcategoria: "PRANCHETA" },
];

function getProdutos() {
  const savedVersao = localStorage.getItem('produtos_versao');
  const saved = localStorage.getItem('produtos');
  // Se o arquivo publicado tem versão nova, atualiza o localStorage
  if (PRODUTOS_VERSAO > 0 && String(savedVersao) !== String(PRODUTOS_VERSAO)) {
    localStorage.setItem('produtos', JSON.stringify(PRODUTOS_INICIAIS));
    localStorage.setItem('produtos_versao', String(PRODUTOS_VERSAO));
    return PRODUTOS_INICIAIS;
  }
  if (saved) return JSON.parse(saved);
  localStorage.setItem('produtos', JSON.stringify(PRODUTOS_INICIAIS));
  localStorage.setItem('produtos_versao', String(PRODUTOS_VERSAO));
  return PRODUTOS_INICIAIS;
}

function setProdutos(lista) {
  localStorage.setItem('produtos', JSON.stringify(lista));
}
